# Generated by Django 4.2.6 on 2023-11-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('done', 'Done')], default='started', max_length=20),
        ),
    ]
