# Generated by Django 4.2.6 on 2023-11-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='creared_by',
            new_name='created_by',
        ),
    ]
