# Generated by Django 4.2.6 on 2023-11-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='DRAFT', max_length=25),
            preserve_default=False,
        ),
    ]
